name: first
on: workflow_dispatch
jobs:
  first-job:
    runs-on:  ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Github"
      - name: Sg
        run: echo "Ola segunda vez amigo
      
      
